apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: english-cafe

images:
- name: myao
  newName: ghcr.io/yuanying/myao
  newTag: 0.8.0

resources:
- src.yaml

secretGenerator:
- name: env
  envs:
  - secrets/.env
